package-lock.json, package.json, src/cardanoLauncher.ts
Closes #10 by using the [same package as Daedalus](https://github.com/input-output-hk/daedalus/blob/develop/package.json#L160) `mkdirp`
=> Replace recursive dir creation with package compatible with Daedalus

test/cli.test.ts, test/integration.test.ts, test/unit.test.ts, test/utils.ts
- Fixes a unit test on windows.
- Fixes an integration test on windows.
- Disables tests which are blocked on #12
=> Make windows CI green

src/cardanoLauncher.ts
=> Add support for cardano-wallet serve --sync-tolerance option

src/cardanoLauncher.ts
=> Use flat structure for state directory

nix/sources.json
The jormungandr version has been updated.
=> Bump cardano-wallet to latest master

src/cardanoLauncher.ts, test/integration.test.ts
=> Don't emit multiple "exit" events

nix/nivpkgs.nix, nix/sources.json, src/byron.ts, test/integration.test.ts
Enable integration test for cardano-wallet-byron, and make it pass.
=> Enable integration test for cardano-wallet-byron

src/cardanoLauncher.ts
=> Add config option to disable signal handlers intercepting termination events

README.md, test/cli.test.ts
- Adds more explanation to the readme
- Adds an informational header comment to `cli.test.ts`.
=> A little extra docs

README.md
Now the first part of Local Development section of the Readme
=> Improve `nix-shell` instruction

.github/workflows/post-release.yml, package-lock.json, package.json
Bumps version for next release, and Closes #35 . Secret has been configured at the repo level
=> Bump version, add post-release workflow to automate package delivery

.github/workflows/ci.yml, README.md, nix/sources.json, package-lock.json, package.json, scripts/download-hydra.js, src/cardanoLauncher.ts, src/cardanoNode.ts, test/cli.test.ts, test/integration.test.ts, test/utils.ts
Fixes #79.
Depends on input-output-hk/cardano-wallet#1884.
=> Add support for cardano-wallet-shelley serve --smash-url

nix/sources.json, scripts/download-hydra.js, src/cardanoLauncher.ts, src/cardanoWallet.ts
Moves cardano-wallet service code into a separate module. This was bothering me, so I wanted to fix it before doing #80.
=> Move cardano-wallet launching code into its own module

scripts/download-hydra.js
Relates to issue #86.
NPM packages which depend on native executables usually need to download and install their files somewhere in `node_modules` via a `package.json` install hook.
I do not really know a good way of writing this install script, but can at least make it possible to fetch the correct files from Hydra.
It's a little bit slow to download but we can make it faster later.
=> Refactor download-hydra.js so that it could be used from npm install

nix/sources.json, src/cardanoWallet.ts, src/common.ts
Fixes ADP-482.
~We set the default for the launcher to "direct fetching", although for the wallet its "none".~
=> Update options to reflect new smash-url configuration

src/cardanoWallet.ts
Related:
* https://github.com/input-output-hk/cardano-wallet/pull/2285
* https://github.com/input-output-hk/iohk-nix/pull/449
=> Update documentation for PoolMetadataSource

nix/nivpkgs.nix, nix/sources.json, nix/sources.nix, shell.nix, test/integration.test.ts
The issue input-output-hk/cardano-node#1086 may be fixed.
=> Remove integration tests shutdown hack

package-lock.json, package.json
=> Bump version: 0.20201014.0 -> 0.20210215.0

nix/sources.json, package-lock.json, package.json
There are 2 dependencies which make dependabot "moderately" unhappy.
This updates the 2 packages which pull in those devDependencies.
Reverse dependencies found with:
```
grep -R '"\(marked\|node-notifier\)"' node_modules/**/package.json
```
=> Silence dependabot

package-lock.json, package.json
ADP-899
1. Bumps the `package.json` version to 0.20210512.0.
2. Fixes some complaints from dependabot.
=> Bump version to 0.20210512.0

nix/sources.json, package-lock.json, package.json
- Bump cardano-wallet to v2021-05-26
- Bump package version to 0.20210528.0
=> Bump cardano-wallet to v2021-05-26

.npmignore, package-lock.json, package.json
In order to keep "dist" folder in the package, I added `.npmignore` so that `.gitignore` is not used in the publishing.
https://docs.npmjs.com/cli/v7/using-npm/developers#keeping-files-out-of-your-package
=> Add dist folder in publish package

.github/PULL_REQUEST_TEMPLATE.md, nix/sources.json, package-lock.json, package.json
Preparation for a new release...
ADP-1334
=> Bump npm package version and cardano-wallet release
